import { createContext, useContext, useMemo, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    language: 'Language',
    english: 'English',
    kurdish: 'Kurdish',
    marketplace: 'Marketplace',
    products: 'Products',
    returns: 'Returns',
    adminPanel: 'Admin Panel',
    cart: 'Cart',
    allRightsReserved: 'All rights reserved.',
    curatedInventory: 'Curated Inventory',
    allProducts: 'All Products',
    details: 'Details',
    add: 'Add',
    noImage: 'No Image',
    loadingProducts: 'Loading products...',
    failedFetchProducts: 'Failed to fetch products',
    loadingProductDetails: 'Loading product details...',
    productNotFound: 'Product not found.',
    back: 'Back',
    addToCart: 'Add to Cart',
    requestToBorrow: 'Request to Borrow',
    yourName: 'Your name',
    requestLoan: 'Request Loan',
    submitting: 'Submitting...',
    loanSubmittedSuccess: 'Loan request submitted successfully!',
    loanSubmitFail: 'Failed to submit loan request.',
    checkout: 'Checkout',
    yourCartEmpty: 'Your cart is empty',
    browseProducts: 'Browse Products',
    orderSummary: 'Order Summary',
    qty: 'Qty',
    remove: 'Remove',
    discountCode: 'Discount Code',
    apply: 'Apply',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax9: 'Tax (9%)',
    total: 'Total',
    completePurchase: 'Complete Purchase',
    processing: 'Processing...',
    invalidCode: 'Invalid code',
    checkoutSuccess: 'Checkout successful! Receipt generated.',
    checkoutFailed: 'Checkout failed.',
    processReturn: 'Process a Return',
    receiptId: 'Receipt ID',
    productId: 'Product ID',
    condition: 'Condition',
    reasonForReturn: 'Reason for Return',
    submitRequest: 'Submit Request',
    returnSubmitted: 'Return request submitted.',
    returnSubmitError: 'Error submitting return',
    unopened: 'Unopened',
    openedGood: 'Opened - Good condition',
    damaged: 'Damaged or Defective',
    adminDashboard: 'Admin Dashboard',
    loanManagement: 'Loan Management',
    loanManagementDesc: 'Review, approve, or reject incoming loan requests for products.',
    manageLoans: 'Manage Loans',
    reportsReceipts: 'Reports & Receipts',
    reportsReceiptsDesc: 'View sales data, top products, and complete receipts.',
    viewReports: 'View Reports',
    productNotesInfo: 'Product Notes & Info',
    productNotesInfoDesc: 'Edit internal admin notes and public product descriptions.',
    editNotes: 'Edit Notes',
    reportsDashboard: 'Reports Dashboard',
    totalRevenue: 'Total Revenue',
    totalTaxCollected: 'Total Tax Collected',
    totalOrders: 'Total Orders',
    topSellingProducts: 'Top Selling Products',
    lowestSellingProducts: 'Lowest Selling Products',
    sold: 'sold',
    noDataAvailable: 'No data available',
    loadingReports: 'Loading reports...',
    loanRequests: 'Loan Requests',
    loadingLoans: 'Loading loans...',
    user: 'User',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    approve: 'Approve',
    reject: 'Reject',
    markReturned: 'Mark Returned',
    noLoanRequests: 'No loan requests found.',
    failedUpdateStatus: 'Failed to update status.',
    pending: 'Pending',
    approved: 'Approved',
    returned: 'Returned',
    rejected: 'Rejected',
    editProductNotesDescriptions: 'Edit Product Notes & Descriptions',
    loadingProductsSimple: 'Loading products...',
    description: 'Description',
    adminNotesInternal: 'Admin Notes (Internal)',
    saveChanges: 'Save Changes',
    productUpdated: 'Product notes/description updated!',
    productUpdateFailed: 'Failed to update product.',
    uploadNewImageMock: 'Upload New Image (Mock)',
    upload: 'Upload',
    uploading: 'Uploading...',
    mockUploadSuccess: 'Mock image uploaded successfully!',
    uploadFailed: 'Upload failed',
    marketManagement: 'Market Management',
    dashboard: 'Dashboard',
    posLabel: 'POS',
    loanSystemLabel: 'Loan System',
    searchPlaceholder: 'Search by name, code, or phone...',
    totalOrdersLabel: 'Total Orders',
    totalSalesLabel: 'Total Sales',
    totalProductsLabel: 'Total Products',
    alertsLabel: 'Alerts',
    reports: 'Reports',
    barcode: 'Barcode',
    productName: 'Product Name',
    currentQty: 'Current Qty',
    units: 'units',
    lastSync: 'Last sync',
    systemOnline: 'System Online',
    posSynced: 'POS terminal synced',
    lowStockWarning: 'Low stock warning',
    time2MinAgo: '2 min ago',
    time8MinAgo: '8 min ago',
    adminRole: 'Admin',
    currency: 'Currency',
    paid: 'Paid',
    remaining: 'Remaining',
    orderCompleted: 'Order completed',
    dashboardOverview: 'Dashboard Overview',
    dashboardSubtitle: 'Control center for POS and market operations',
    posSystem: 'POS System',
    posSystemSubtitle: 'Create orders, manage cart, and checkout quickly',
    loanSystem: 'Loan System',
    loanSystemSubtitle: 'Monitor customer loans and payment status',
    productsSubtitle: 'Track products, stock, and prices',
    categoriesSubtitle: 'Manage product category groups',
    companiesSubtitle: 'Supplier and company directory',
    usersSubtitle: 'Team members and roles',
    settingsSubtitle: 'Basic store settings and controls',
    logout: 'Log Out',
    dashboard: 'Dashboard',
    search: 'Search',
    orders: 'Orders',
    sales: 'Sales',
    inventory: 'Inventory',
    alerts: 'Alerts',
    quickAccessHub: 'Quick Access Hub',
    price: 'Price',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    customer: 'Customer',
    amount: 'Amount',
    loanType: 'Loan Type',
    phone: 'Phone',
    dueDate: 'Due Date',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    storeSettings: 'Store Settings',
    storeName: 'Store Name',
    storeEmail: 'Store Email',
    businessLicense: 'Business License',
    saveSettings: 'Save Settings',
    cartEmpty: 'Cart is empty',
    items: 'Items',
    currency: 'Currency',
    lowStockProducts: 'Low Stock Products',
    itemsWithLowQty: 'Items with quantity less than 10 units',
    liveActivity: 'Live Activity',
    systemNotifications: 'System and operation notifications',
    paid: 'Paid',
    remaining: 'Remaining',
    categories: 'Categories',
    companies: 'Companies',
    users: 'Users',
    settings: 'Settings'
  },
  ku: {
    language: 'زمان',
    english: 'ئینگلیزی',
    kurdish: 'کوردی',
    marketplace: 'بازاڕگا',
    products: 'بەرهەمەکان',
    returns: 'گەڕانەوە',
    adminPanel: 'پانێڵی ئەدمین',
    cart: 'سەبەتە',
    allRightsReserved: 'هەموو مافەکان پارێزراون.',
    curatedInventory: 'کۆلەکسیونی هەڵبژێردراو',
    allProducts: 'هەموو بەرهەمەکان',
    details: 'وردەکارییەکان',
    add: 'زیادکردن',
    noImage: 'وێنە نییە',
    loadingProducts: 'بەرهەمەکان بار دەکات...',
    failedFetchProducts: 'هەنار هەناڕ بەرهەمەکان سەرکەفتو نەبوو',
    loadingProductDetails: 'وردەکارییەکانی بەرهەم بار دەکات...',
    productNotFound: 'بەرهەم نەدۆزرایەوە.',
    back: 'گەڕانەوە',
    addToCart: 'زیادکردن بۆ سەبەت',
    requestToBorrow: 'داواکاری بۆ قەرزگیرتن',
    yourName: 'ناوی تۆ',
    requestLoan: 'داواکاری قەرز',
    submitting: 'ناردن...',
    loanSubmittedSuccess: 'داواکاری قەرز بە سەرکەفتی ناردرا!',
    loanSubmitFail: 'ناردنی داواکاری قەرز سەرکەفتو نەبوو.',
    checkout: 'پارەدان',
    yourCartEmpty: 'سەبەتی تۆ بەتاڵە',
    browseProducts: 'گەڕان بۆ بەرهەمەکان',
    orderSummary: 'کورتەی داویکاری',
    qty: 'ژمارە',
    remove: 'لابردن',
    discountCode: 'کۆدی داشتناوا',
    apply: 'جەبەجەکردن',
    subtotal: 'کۆی سەرەتایی',
    discount: 'داشتناوا',
    tax9: 'باج (9%)',
    total: 'کۆی گشتی',
    completePurchase: 'تەواوبوونی کڕین',
    processing: 'کارکردن...',
    invalidCode: 'کۆد دروست نییە',
    checkoutSuccess: 'پارەدان سەرکەفتی بو! وسیل دروست کرا.',
    checkoutFailed: 'پارەدان سەرکەفتو نەبوو.',
    processReturn: 'پەسەندکردنی گەڕانەوە',
    receiptId: 'ناسنامەی وسیل',
    productId: 'ناسنامەی بەرهەم',
    condition: 'دۆخ',
    reasonForReturn: 'هۆکاری گەڕانەوە',
    submitRequest: 'ناردنی داواکاری',
    returnSubmitted: 'داواکاری گەڕانەوە ناردرا.',
    returnSubmitError: 'هەڵە لە ناردنی گەڕانەوە',
    unopened: 'نەکراوە',
    openedGood: 'کراوە - بە دۆخی باش',
    damaged: 'خراپ یان کەل',
    adminDashboard: 'داشکانی ئەدمین',
    loanManagement: 'بەڕێوەبردنی قەرز',
    loanManagementDesc: 'پشکنین، پەسەندکردن، یان ڕەتکردنەوەی داواکارییەکانی قەرزی بەرهەمەکان.',
    manageLoans: 'بەڕێوەبردنی قەرز',
    reportsReceipts: 'ڕاپۆرت و وسیل',
    reportsReceiptsDesc: 'دانیاری کڕین، بەرهەمی زۆربەفروشت، و هەموو وسیلەکان ببینە.',
    viewReports: 'بینینی ڕاپۆرتەکان',
    productNotesInfo: 'تێبینی بەرهەم و زانیاری',
    productNotesInfoDesc: 'تێبینی ناوخۆی ئەدمین و وەسفی گشتی بەرهەمەکان دەستکاری بکە.',
    editNotes: 'دەستکاری تێبینی',
    reportsDashboard: 'پانێڵی ڕاپۆرت',
    totalRevenue: 'داهاتی گشتی',
    totalTaxCollected: 'کۆی باجی کۆمکراو',
    totalOrders: 'کۆی داویکاری',
    topSellingProducts: 'بەرهەمی زۆربەفروشت',
    lowestSellingProducts: 'بەرهەمی کەمبەفروشت',
    sold: 'فروشرا',
    noDataAvailable: 'دانیاری نییە',
    loadingReports: 'ڕاپۆرت بار دەکات...',
    loanRequests: 'داواکاری قەرز',
    loadingLoans: 'قەرزەکان بار دەکات...',
    user: 'بەکارهێنەر',
    date: 'ڕۆژ',
    status: 'بارودۆخ',
    actions: 'کردار',
    approve: 'پەسەندکردن',
    reject: 'ڕەتکردنەوە',
    markReturned: 'نیشانکردنی گەڕاوە',
    noLoanRequests: 'هیچ داواکاری قەرز نییە.',
    failedUpdateStatus: 'نوێکردنەوەی بارودۆخ سەرکەفتو نەبوو.',
    pending: 'چاوەڕوان',
    approved: 'پەسەندکراو',
    returned: 'گەڕاوە',
    rejected: 'ڕەتکراوە',
    editProductNotesDescriptions: 'دەستکاری تێبینی و وەسفی بەرهەم',
    loadingProductsSimple: 'بەرهەمەکان بار دەکات...',
    description: 'وەسف',
    adminNotesInternal: 'تێبینی ئەدمین (ناوخۆ)',
    saveChanges: 'پاراستنی گۆڕانکارییەکان',
    productUpdated: 'تێبینی/وەسفی بەرهەم نوێ کرا!',
    productUpdateFailed: 'نوێکردنەوەی بەرهەم سەرکەفتو نەبوو.',
    uploadNewImageMock: 'بارکردنی وێنەی نوێ (Mock)',
    upload: 'بارکردن',
    uploading: 'بار دەکات...',
    mockUploadSuccess: 'بارکردنی وێنە بە سەرکەفتی تەواو بو!',
    uploadFailed: 'بارکردن سەرکەفتو نەبوو',
    dashboardOverview: 'بەند داشکانی بیرۆکە',
    dashboardSubtitle: 'مەرکەز کنترۆل بۆ سیستمی فرۆش و کارەبازاڕ',
    posSystem: 'سیستمی فرۆش',
    posSystemSubtitle: 'دروستکردنی داویکاری، بەڕێوەبردنی سەبەت، و پارەدانی خێرا',
    loanSystem: 'سیستمی قەرز',
    loanSystemSubtitle: 'نیگەرانی قەرزی مامۆستایان و بارودۆخی پارەدان',
    productsSubtitle: 'شارەزای بەرهەمەکان، لیستە، و نرخ',
    categoriesSubtitle: 'بەڕێوەبردنی کۆمپۆنەنتی بەرهەم',
    companiesSubtitle: 'ڕێکلامی کۆمپانیا و فرۆشندە',
    usersSubtitle: 'ئەنجامدەرەکانی تیم و رۆلی کار',
    settingsSubtitle: 'ڕێکخستنی بنەڕەتی فرۆشگە و کنترۆلەکان',
    logout: 'دەرچوون',
    dashboard: 'داشکان',
    search: 'گەڕان',
    orders: 'داویکاری',
    sales: 'فرۆش',
    inventory: 'لیستە',
    alerts: 'ئاگاداری',
    quickAccessHub: 'هوبی دەست‌رەسی خێرا',
    price: 'نرخ',
    inStock: 'لە لیستەدا',
    outOfStock: 'لە لیستەدا نیە',
    customer: 'مامۆستای',
    amount: 'بڕی',
    loanType: 'جۆری قەرز',
    phone: 'تێلیفۆن',
    dueDate: 'بەرواری سەپاندن',
    name: 'ناو',
    email: 'ئیمەیل',
    role: 'رۆل',
    storeSettings: 'ڕێکخستنی فرۆشگە',
    storeName: 'ناوی فرۆشگە',
    storeEmail: 'ئیمەیلی فرۆشگە',
    businessLicense: 'لیسانسی کار',
    saveSettings: 'پاراستنی ڕێکخستنەکان',
    cartEmpty: 'سەبەت بەتاڵە',
    items: 'بریار',
    currency: 'درێمە',
    lowStockProducts: 'بەرهەمەکانی لیستەی کەم',
    itemsWithLowQty: 'بریاری تەن کۆم لە 10 یادا',
    liveActivity: 'چالاکبوونی زیندۆ',
    systemNotifications: 'بریاری سیستەم و کارەبازاڕ',
    paid: 'پارەدراو',
    remaining: 'ماوەی',
    categories: 'تاقگەکان',
    companies: 'لیسانسەها',
    users: 'بەکارهێنان',
    settings: 'ڕێکخستنەکان',
    barcode: 'Barcode',
    productName: 'Product Name',
    currentQty: 'Current Qty',
    stock: 'Stock',
    code: 'Code',
    lastSync: 'Last sync',
    systemOnline: 'System Online'
  },
  ku: {
    language: 'زمان',
    english: 'ئینگلیزی',
    kurdish: 'کوردی',
    marketplace: 'بازاڕگا',
    products: 'بەرهەمەکان',
    returns: 'گەڕانەوە',
    adminPanel: 'پانێڵی ئەدمین',
    cart: 'سەبەتە',
    allRightsReserved: 'هەموو مافەکان پارێزراون.',
    curatedInventory: 'کۆلەکسیونی هەڵبژێردراو',
    allProducts: 'هەموو بەرهەمەکان',
    details: 'وردەکارییەکان',
    add: 'زیادکردن',
    noImage: 'وێنە نییە',
    loadingProducts: 'بەرهەمەکان بار دەکات...',
    failedFetchProducts: 'هەنار هەناڕ بەرهەمەکان سەرکەفتو نەبوو',
    loadingProductDetails: 'وردەکارییەکانی بەرهەم بار دەکات...',
    productNotFound: 'بەرهەم نەدۆزرایەوە.',
    back: 'گەڕانەوە',
    addToCart: 'زیادکردن بۆ سەبەت',
    requestToBorrow: 'داواکاری بۆ قەرزگیرتن',
    yourName: 'ناوی تۆ',
    requestLoan: 'داواکاری قەرز',
    submitting: 'ناردن...',
    loanSubmittedSuccess: 'داواکاری قەرز بە سەرکەفتی ناردرا!',
    loanSubmitFail: 'ناردنی داواکاری قەرز سەرکەفتو نەبوو.',
    checkout: 'پارەدان',
    yourCartEmpty: 'سەبەتی تۆ بەتاڵە',
    browseProducts: 'گەڕان بۆ بەرهەمەکان',
    orderSummary: 'کورتەی داویکاری',
    qty: 'ژمارە',
    remove: 'لابردن',
    discountCode: 'کۆدی داشتناوا',
    apply: 'جەبەجەکردن',
    subtotal: 'کۆی سەرەتایی',
    discount: 'داشتناوا',
    tax9: 'باج (9%)',
    total: 'کۆی گشتی',
    completePurchase: 'تەواوبوونی کڕین',
    processing: 'کارکردن...',
    invalidCode: 'کۆد دروست نییە',
    checkoutSuccess: 'پارەدان سەرکەفتی بو! وسیل دروست کرا.',
    checkoutFailed: 'پارەدان سەرکەفتو نەبوو.',
    processReturn: 'پەسەندکردنی گەڕانەوە',
    receiptId: 'ناسنامەی وسیل',
    productId: 'ناسنامەی بەرهەم',
    condition: 'دۆخ',
    reasonForReturn: 'هۆکاری گەڕانەوە',
    submitRequest: 'ناردنی داواکاری',
    returnSubmitted: 'داواکاری گەڕانەوە ناردرا.',
    returnSubmitError: 'هەڵە لە ناردنی گەڕانەوە',
    unopened: 'نەکراوە',
    openedGood: 'کراوە - بە دۆخی باش',
    damaged: 'خراپ یان کەل',
    adminDashboard: 'داشکانی ئەدمین',
    loanManagement: 'بەڕێوەبردنی قەرز',
    loanManagementDesc: 'پشکنین، پەسەندکردن، یان ڕەتکردنەوەی داواکارییەکانی قەرزی بەرهەمەکان.',
    manageLoans: 'بەڕێوەبردنی قەرز',
    reportsReceipts: 'ڕاپۆرت و وسیل',
    reportsReceiptsDesc: 'دانیاری کڕین، بەرهەمی زۆربەفروشت، و هەموو وسیلەکان ببینە.',
    viewReports: 'بینینی ڕاپۆرتەکان',
    productNotesInfo: 'تێبینی بەرهەم و زانیاری',
    productNotesInfoDesc: 'تێبینی ناوخۆی ئەدمین و وەسفی گشتی بەرهەمەکان دەستکاری بکە.',
    editNotes: 'دەستکاری تێبینی',
    reportsDashboard: 'پانێڵی ڕاپۆرت',
    totalRevenue: 'داهاتی گشتی',
    totalTaxCollected: 'کۆی باجی کۆمکراو',
    totalOrders: 'کۆی داویکاری',
    topSellingProducts: 'بەرهەمی زۆربەفروشت',
    lowestSellingProducts: 'بەرهەمی کەمبەفروشت',
    sold: 'فروشرا',
    noDataAvailable: 'دانیاری نییە',
    loadingReports: 'ڕاپۆرت بار دەکات...',
    loanRequests: 'داواکاری قەرز',
    loadingLoans: 'قەرزەکان بار دەکات...',
    user: 'بەکارهێنەر',
    date: 'ڕۆژ',
    status: 'بارودۆخ',
    actions: 'کردار',
    approve: 'پەسەندکردن',
    reject: 'ڕەتکردنەوە',
    markReturned: 'نیشانکردنی گەڕاوە',
    noLoanRequests: 'هیچ داواکاری قەرز نییە.',
    failedUpdateStatus: 'نوێکردنەوەی بارودۆخ سەرکەفتو نەبوو.',
    pending: 'چاوەڕوان',
    approved: 'پەسەندکراو',
    returned: 'گەڕاوە',
    rejected: 'ڕەتکراوە',
    editProductNotesDescriptions: 'دەستکاری تێبینی و وەسفی بەرهەم',
    loadingProductsSimple: 'بەرهەمەکان بار دەکات...',
    description: 'وەسف',
    adminNotesInternal: 'تێبینی ئەدمین (ناوخۆ)',
    saveChanges: 'پاراستنی گۆڕانکارییەکان',
    productUpdated: 'تێبینی/وەسفی بەرهەم نوێ کرا!',
    productUpdateFailed: 'نوێکردنەوەی بەرهەم سەرکەفتو نەبوو.',
    uploadNewImageMock: 'بارکردنی وێنەی نوێ (Mock)',
    upload: 'بارکردن',
    uploading: 'بار دەکات...',
    mockUploadSuccess: 'بارکردنی وێنە بە سەرکەفتی تەواو بو!',
    uploadFailed: 'بارکردن سەرکەفتو نەبوو',
    dashboardOverview: 'بەند داشکانی بیرۆکە',
    dashboardSubtitle: 'مەرکەز کنترۆل بۆ سیستمی فرۆش و کارەبازاڕ',
    posSystem: 'سیستمی فرۆش',
    posSystemSubtitle: 'دروستکردنی داویکاری، بەڕێوەبردنی سەبەت، و پارەدانی خێرا',
    loanSystem: 'سیستمی قەرز',
    loanSystemSubtitle: 'نیگەرانی قەرزی مامۆستایان و بارودۆخی پارەدان',
    productsSubtitle: 'شارەزای بەرهەمەکان، لیستە، و نرخ',
    categoriesSubtitle: 'بەڕێوەبردنی کۆمپۆنەنتی بەرهەم',
    companiesSubtitle: 'ڕێکلامی کۆمپانیا و فرۆشندە',
    usersSubtitle: 'ئەنجامدەرەکانی تیم و رۆلی کار',
    settingsSubtitle: 'ڕێکخستنی بنەڕەتی فرۆشگە و کنترۆلەکان',
    logout: 'دەرچوون',
    dashboard: 'داشکان',
    search: 'گەڕان',
    orders: 'داویکاری',
    sales: 'فرۆش',
    inventory: 'لیستە',
    alerts: 'ئاگاداری',
    quickAccessHub: 'هوبی دەست‌رەسی خێرا',
    price: 'نرخ',
    inStock: 'لە لیستەدا',
    outOfStock: 'لە لیستەدا نیە',
    customer: 'مامۆستای',
    amount: 'بڕی',
    loanType: 'جۆری قەرز',
    phone: 'تێلیفۆن',
    dueDate: 'بەرواری سەپاندن',
    name: 'ناو',
    email: 'ئیمەیل',
    role: 'رۆل',
    storeSettings: 'ڕێکخستنی فرۆشگە',
    storeName: 'ناوی فرۆشگە',
    storeEmail: 'ئیمەیلی فرۆشگە',
    businessLicense: 'لیسانسی کار',
    saveSettings: 'پاراستنی ڕێکخستنەکان',
    cartEmpty: 'سەبەت بەتاڵە',
    items: 'بریار',
    currency: 'درێمە',
    lowStockProducts: 'بەرهەمەکانی لیستەی کەم',
    itemsWithLowQty: 'بریاری تەن کۆم لە 10 یادا',
    liveActivity: 'چالاکبوونی زیندۆ',
    systemNotifications: 'بریاری سیستەم و کارەبازاڕ',
    paid: 'پارەدراو',
    remaining: 'ماوەی',
    categories: 'تاقگەکان',
    companies: 'لیسانسەها',
    users: 'بەکارهێنان',
    settings: 'ڕێکخستنەکان',
    barcode: 'بارکۆد',
    productName: 'ناوی بەرهەم',
    currentQty: 'ژمارەی ئێستا',
    units: 'یەکە',
    stock: 'لیستە',
    code: 'کۆد',
    lastSync: 'دوایین هاوڕێی',
    systemOnline: 'سیستەم بەڕووبار',
    marketManagement: 'بەڕێوەبردنی بازاڕ',
    dashboard: 'داشکان',
    posLabel: 'فرۆش',
    loanSystemLabel: 'سیستمی قەرز',
    searchPlaceholder: 'گەڕان بە ناو، کۆد، یان تێلیفۆن...',
    totalOrdersLabel: 'کۆی داویکاری',
    totalSalesLabel: 'کۆی فرۆش',
    totalProductsLabel: 'کۆی بەرهەمەکان',
    alertsLabel: 'ئاگاداری',
    reports: 'ڕاپۆرت',
    posSynced: 'ترمینالی فرۆش هاوڕێ بوو',
    lowStockWarning: 'ئاگاداری کەمبوونی لیستە',
    time2MinAgo: '٢ خولەک پێشوو',
    time8MinAgo: '٨ خولەک پێشوو',
    adminRole: 'ئەدمین',
    orderCompleted: 'داویکاری تەواو بوو'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = useMemo(() => {
    return (key) => translations[language]?.[key] ?? translations.en[key] ?? key;
  }, [language]);

  useEffect(() => {
    document.body.setAttribute('data-lang', language);
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
