import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    language: 'Language',
    english: 'English',
    kurdish: 'Kurdish',
    marketplace: 'Marketplace',
    products: 'Products',
    returns: 'Returns',
    adminPanel: 'Admin Panel',
    cart: 'Cart',
    allRightsReserved: 'All rights reserved.',
    curatedInventory: 'Curated Inventory',
    allProducts: 'All Products',
    details: 'Details',
    add: 'Add',
    noImage: 'No Image',
    loadingProducts: 'Loading products...',
    failedFetchProducts: 'Failed to fetch products',
    loadingProductDetails: 'Loading product details...',
    productNotFound: 'Product not found.',
    back: 'Back',
    addToCart: 'Add to Cart',
    requestToBorrow: 'Request to Borrow',
    yourName: 'Your name',
    requestLoan: 'Request Loan',
    submitting: 'Submitting...',
    loanSubmittedSuccess: 'Loan request submitted successfully!',
    loanSubmitFail: 'Failed to submit loan request.',
    checkout: 'Checkout',
    yourCartEmpty: 'Your cart is empty',
    browseProducts: 'Browse Products',
    orderSummary: 'Order Summary',
    qty: 'Qty',
    remove: 'Remove',
    discountCode: 'Discount Code',
    apply: 'Apply',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax9: 'Tax (9%)',
    total: 'Total',
    completePurchase: 'Complete Purchase',
    processing: 'Processing...',
    invalidCode: 'Invalid code',
    checkoutSuccess: 'Checkout successful! Receipt generated.',
    checkoutFailed: 'Checkout failed.',
    processReturn: 'Process a Return',
    receiptId: 'Receipt ID',
    productId: 'Product ID',
    condition: 'Condition',
    reasonForReturn: 'Reason for Return',
    submitRequest: 'Submit Request',
    returnSubmitted: 'Return request submitted.',
    returnSubmitError: 'Error submitting return',
    unopened: 'Unopened',
    openedGood: 'Opened - Good condition',
    damaged: 'Damaged or Defective',
    adminDashboard: 'Admin Dashboard',
    loanManagement: 'Loan Management',
    loanManagementDesc: 'Review, approve, or reject incoming loan requests for products.',
    manageLoans: 'Manage Loans',
    reportsReceipts: 'Reports & Receipts',
    reportsReceiptsDesc: 'View sales data, top products, and complete receipts.',
    viewReports: 'View Reports',
    productNotesInfo: 'Product Notes & Info',
    productNotesInfoDesc: 'Edit internal admin notes and public product descriptions.',
    editNotes: 'Edit Notes',
    reportsDashboard: 'Reports Dashboard',
    totalRevenue: 'Total Revenue',
    totalTaxCollected: 'Total Tax Collected',
    totalOrders: 'Total Orders',
    topSellingProducts: 'Top Selling Products',
    lowestSellingProducts: 'Lowest Selling Products',
    sold: 'sold',
    noDataAvailable: 'No data available',
    loadingReports: 'Loading reports...',
    loanRequests: 'Loan Requests',
    loadingLoans: 'Loading loans...',
    user: 'User',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    approve: 'Approve',
    reject: 'Reject',
    markReturned: 'Mark Returned',
    noLoanRequests: 'No loan requests found.',
    failedUpdateStatus: 'Failed to update status.',
    pending: 'Pending',
    approved: 'Approved',
    returned: 'Returned',
    rejected: 'Rejected',
    editProductNotesDescriptions: 'Edit Product Notes & Descriptions',
    loadingProductsSimple: 'Loading products...',
    description: 'Description',
    adminNotesInternal: 'Admin Notes (Internal)',
    saveChanges: 'Save Changes',
    productUpdated: 'Product notes/description updated!',
    productUpdateFailed: 'Failed to update product.',
    uploadNewImageMock: 'Upload New Image (Mock)',
    upload: 'Upload',
    uploading: 'Uploading...',
    mockUploadSuccess: 'Mock image uploaded successfully!',
    uploadFailed: 'Upload failed'
  },
  ku: {
    language: 'Ziman',
    english: 'Inglizi',
    kurdish: 'Kurdi',
    marketplace: 'Bazargah',
    products: 'Berhemekan',
    returns: 'Gerinawa',
    adminPanel: 'Paneli Admin',
    cart: 'Sebet',
    allRightsReserved: 'Hemuy mafekan parastin.',
    curatedInventory: 'Koleksyoni Helbijerde',
    allProducts: 'Hemuy Berhemekan',
    details: 'Detay',
    add: 'Zyadke',
    noImage: 'Wene niye',
    loadingProducts: 'Berhemekan bar dakat...',
    failedFetchProducts: 'Henarhena berhemekan serkeftu nabu',
    loadingProductDetails: 'Detayli berhem bar dakat...',
    productNotFound: 'Berhem nedozrayewa.',
    back: 'Gerewe',
    addToCart: 'Bixe Sebet',
    requestToBorrow: 'Dawakar bo Qerzgirtin',
    yourName: 'Nawi to',
    requestLoan: 'Nardni Dawa',
    submitting: 'Nerdra...',
    loanSubmittedSuccess: 'Dawayi qerz ba serkefti nardra!',
    loanSubmitFail: 'Nardni dawayi qerz serkeftu nabu.',
    checkout: 'Paradan',
    yourCartEmpty: 'Sebeti to boşe',
    browseProducts: 'Garan bo Berhemekan',
    orderSummary: 'Kurteyi Dawekari',
    qty: 'Jmare',
    remove: 'Labrda',
    discountCode: 'Kodi Dashtnawa',
    apply: 'Jebejeke',
    subtotal: 'Koyi seretai',
    discount: 'Dashtnawa',
    tax9: 'Bac (9%)',
    total: 'Koyi Gshti',
    completePurchase: 'Tevawkirni Krrin',
    processing: 'Karekra...',
    invalidCode: 'Kod drust nist',
    checkoutSuccess: 'Paradan serkeftu bu! Wsil drust kra.',
    checkoutFailed: 'Paradan serkeftu nabu.',
    processReturn: 'Peshkeshkirni Gerinawa',
    receiptId: 'Nasnami Wsil',
    productId: 'Nasnami Berhem',
    condition: 'Dox',
    reasonForReturn: 'Hokari Gerinawa',
    submitRequest: 'Nardni Dawa',
    returnSubmitted: 'Dawayi gerinawa nardra.',
    returnSubmitError: 'Hela le nardni gerinawa',
    unopened: 'Nekrawa',
    openedGood: 'Krawa - ba doxi bash',
    damaged: 'Xrap yan Kel',
    adminDashboard: 'Dashtkari Admin',
    loanManagement: 'Barewbrdni Qerz',
    loanManagementDesc: 'Pshkni, pesend yakhud radkirni dawakari qerz bo berhemekan.',
    manageLoans: 'Barewbrdni Qerz',
    reportsReceipts: 'Raport u Wsil',
    reportsReceiptsDesc: 'Daniyari krrin, berhemi zorbefrosh, u hemu wsilekan bibine.',
    viewReports: 'Bini Raportekan',
    productNotesInfo: 'Tebini Berhem u Zaniyari',
    productNotesInfoDesc: 'Tebini nawxo u wasfi giyshti berhemekan destkari bike.',
    editNotes: 'Destkarii Tebini',
    reportsDashboard: 'Paneli Raport',
    totalRevenue: 'Dahati Gshti',
    totalTaxCollected: 'Koyi Baci Komkraw',
    totalOrders: 'Koyi Dawekari',
    topSellingProducts: 'Berhemi Zorbefrosh',
    lowestSellingProducts: 'Berhemi Kemfroshtir',
    sold: 'froshraw',
    noDataAvailable: 'Daniyar nist',
    loadingReports: 'Raport bar dakat...',
    loanRequests: 'Dawakari Qerz',
    loadingLoans: 'Qerzekan bar dakat...',
    user: 'Bekarhener',
    date: 'Roj',
    status: 'Barodox',
    actions: 'Kirdar',
    approve: 'Pesend',
    reject: 'Radkirdnawa',
    markReturned: 'Nishankrdni Gerawa',
    noLoanRequests: 'Hiç dawakari qerz niye.',
    failedUpdateStatus: 'Nwenewekrdni barodox serkeftu nabu.',
    pending: 'Chawerwan',
    approved: 'Pesendkraw',
    returned: 'Gerawa',
    rejected: 'Radkrawa',
    editProductNotesDescriptions: 'Destkarii Tebini u Wasfi Berhem',
    loadingProductsSimple: 'Berhemekan bar dakat...',
    description: 'Wasf',
    adminNotesInternal: 'Tebini Admin (Nawxo)',
    saveChanges: 'Parastni Goranakari',
    productUpdated: 'Tebini/wasfi berhem nwene kra!',
    productUpdateFailed: 'Nwenewekrdni berhem serkeftu nabu.',
    uploadNewImageMock: 'Barakrdni Wenei Nwe (Mock)',
    upload: 'Barbkere',
    uploading: 'Bar dakat...',
    mockUploadSuccess: 'Barakrdni wene ba serkefti temam bu!',
    uploadFailed: 'Barakrdn serkeftu nabu'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = useMemo(() => {
    return (key) => translations[language]?.[key] ?? translations.en[key] ?? key;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
