import { createContext, useContext, useMemo, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    language: 'Language',
    english: 'English',
    kurdish: 'Kurdish',
    marketplace: 'Marketplace',
    products: 'Products',
    returns: 'Returns',
    adminPanel: 'Admin Panel',
    cart: 'Cart',
    allRightsReserved: 'All rights reserved.',
    curatedInventory: 'Curated Inventory',
    allProducts: 'All Products',
    details: 'Details',
    add: 'Add',
    noImage: 'No Image',
    loadingProducts: 'Loading products...',
    failedFetchProducts: 'Failed to fetch products',
    loadingProductDetails: 'Loading product details...',
    productNotFound: 'Product not found.',
    back: 'Back',
    addToCart: 'Add to Cart',
    requestToBorrow: 'Request to Borrow',
    yourName: 'Your name',
    requestLoan: 'Request Loan',
    submitting: 'Submitting...',
    loanSubmittedSuccess: 'Loan request submitted successfully!',
    loanSubmitFail: 'Failed to submit loan request.',
    checkout: 'Checkout',
    yourCartEmpty: 'Your cart is empty',
    browseProducts: 'Browse Products',
    orderSummary: 'Order Summary',
    qty: 'Qty',
    remove: 'Remove',
    discountCode: 'Discount Code',
    apply: 'Apply',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax9: 'Tax (9%)',
    total: 'Total',
    completePurchase: 'Complete Purchase',
    processing: 'Processing...',
    invalidCode: 'Invalid code',
    checkoutSuccess: 'Checkout successful! Receipt generated.',
    checkoutFailed: 'Checkout failed.',
    processReturn: 'Process a Return',
    receiptId: 'Receipt ID',
    productId: 'Product ID',
    condition: 'Condition',
    reasonForReturn: 'Reason for Return',
    submitRequest: 'Submit Request',
    returnSubmitted: 'Return request submitted.',
    returnSubmitError: 'Error submitting return',
    unopened: 'Unopened',
    openedGood: 'Opened - Good condition',
    damaged: 'Damaged or Defective',
    adminDashboard: 'Admin Dashboard',
    loanManagement: 'Loan Management',
    loanManagementDesc: 'Review, approve, or reject incoming loan requests for products.',
    manageLoans: 'Manage Loans',
    reportsReceipts: 'Reports & Receipts',
    reportsReceiptsDesc: 'View sales data, top products, and complete receipts.',
    viewReports: 'View Reports',
    productNotesInfo: 'Product Notes & Info',
    productNotesInfoDesc: 'Edit internal admin notes and public product descriptions.',
    editNotes: 'Edit Notes',
    reportsDashboard: 'Reports Dashboard',
    totalRevenue: 'Total Revenue',
    totalTaxCollected: 'Total Tax Collected',
    totalOrders: 'Total Orders',
    topSellingProducts: 'Top Selling Products',
    lowestSellingProducts: 'Lowest Selling Products',
    sold: 'sold',
    noDataAvailable: 'No data available',
    loadingReports: 'Loading reports...',
    loanRequests: 'Loan Requests',
    loadingLoans: 'Loading loans...',
    user: 'User',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    approve: 'Approve',
    reject: 'Reject',
    markReturned: 'Mark Returned',
    noLoanRequests: 'No loan requests found.',
    failedUpdateStatus: 'Failed to update status.',
    pending: 'Pending',
    approved: 'Approved',
    returned: 'Returned',
    rejected: 'Rejected',
    editProductNotesDescriptions: 'Edit Product Notes & Descriptions',
    loadingProductsSimple: 'Loading products...',
    description: 'Description',
    adminNotesInternal: 'Admin Notes (Internal)',
    saveChanges: 'Save Changes',
    productUpdated: 'Product notes/description updated!',
    productUpdateFailed: 'Failed to update product.',
    uploadNewImageMock: 'Upload New Image (Mock)',
    upload: 'Upload',
    uploading: 'Uploading...',
    mockUploadSuccess: 'Mock image uploaded successfully!',
    uploadFailed: 'Upload failed'
  },
  ku: {
    language: 'زمان',
    english: 'ئینگلیزی',
    kurdish: 'کوردی',
    marketplace: 'بازاڕگا',
    products: 'بەرهەمەکان',
    returns: 'گەڕانەوە',
    adminPanel: 'پانێڵی ئەدمین',
    cart: 'سەبەتە',
    allRightsReserved: 'هەموو مافەکان پارێزراون.',
    curatedInventory: 'کۆلەکسیونی هەڵبژێردراو',
    allProducts: 'هەموو بەرهەمەکان',
    details: 'وردەکارییەکان',
    add: 'زیادکردن',
    noImage: 'وێنە نییە',
    loadingProducts: 'بەرهەمەکان بار دەکات...',
    failedFetchProducts: 'هەنار هەناڕ بەرهەمەکان سەرکەفتو نەبوو',
    loadingProductDetails: 'وردەکارییەکانی بەرهەم بار دەکات...',
    productNotFound: 'بەرهەم نەدۆزرایەوە.',
    back: 'گەڕانەوە',
    addToCart: 'زیادکردن بۆ سەبەت',
    requestToBorrow: 'داواکاری بۆ قەرزگیرتن',
    yourName: 'ناوی تۆ',
    requestLoan: 'داواکاری قەرز',
    submitting: 'ناردن...',
    loanSubmittedSuccess: 'داواکاری قەرز بە سەرکەفتی ناردرا!',
    loanSubmitFail: 'ناردنی داواکاری قەرز سەرکەفتو نەبوو.',
    checkout: 'پارەدان',
    yourCartEmpty: 'سەبەتی تۆ بەتاڵە',
    browseProducts: 'گەڕان بۆ بەرهەمەکان',
    orderSummary: 'کورتەی داویکاری',
    qty: 'ژمارە',
    remove: 'لابردن',
    discountCode: 'کۆدی داشتناوا',
    apply: 'جەبەجەکردن',
    subtotal: 'کۆی سەرەتایی',
    discount: 'داشتناوا',
    tax9: 'باج (9%)',
    total: 'کۆی گشتی',
    completePurchase: 'تەواوبوونی کڕین',
    processing: 'کارکردن...',
    invalidCode: 'کۆد دروست نییە',
    checkoutSuccess: 'پارەدان سەرکەفتی بو! وسیل دروست کرا.',
    checkoutFailed: 'پارەدان سەرکەفتو نەبوو.',
    processReturn: 'پەسەندکردنی گەڕانەوە',
    receiptId: 'ناسنامەی وسیل',
    productId: 'ناسنامەی بەرهەم',
    condition: 'دۆخ',
    reasonForReturn: 'هۆکاری گەڕانەوە',
    submitRequest: 'ناردنی داواکاری',
    returnSubmitted: 'داواکاری گەڕانەوە ناردرا.',
    returnSubmitError: 'هەڵە لە ناردنی گەڕانەوە',
    unopened: 'نەکراوە',
    openedGood: 'کراوە - بە دۆخی باش',
    damaged: 'خراپ یان کەل',
    adminDashboard: 'داشکانی ئەدمین',
    loanManagement: 'بەڕێوەبردنی قەرز',
    loanManagementDesc: 'پشکنین، پەسەندکردن، یان ڕەتکردنەوەی داواکارییەکانی قەرزی بەرهەمەکان.',
    manageLoans: 'بەڕێوەبردنی قەرز',
    reportsReceipts: 'ڕاپۆرت و وسیل',
    reportsReceiptsDesc: 'دانیاری کڕین، بەرهەمی زۆربەفروشت، و هەموو وسیلەکان ببینە.',
    viewReports: 'بینینی ڕاپۆرتەکان',
    productNotesInfo: 'تێبینی بەرهەم و زانیاری',
    productNotesInfoDesc: 'تێبینی ناوخۆی ئەدمین و وەسفی گشتی بەرهەمەکان دەستکاری بکە.',
    editNotes: 'دەستکاری تێبینی',
    reportsDashboard: 'پانێڵی ڕاپۆرت',
    totalRevenue: 'داهاتی گشتی',
    totalTaxCollected: 'کۆی باجی کۆمکراو',
    totalOrders: 'کۆی داویکاری',
    topSellingProducts: 'بەرهەمی زۆربەفروشت',
    lowestSellingProducts: 'بەرهەمی کەمبەفروشت',
    sold: 'فروشرا',
    noDataAvailable: 'دانیاری نییە',
    loadingReports: 'ڕاپۆرت بار دەکات...',
    loanRequests: 'داواکاری قەرز',
    loadingLoans: 'قەرزەکان بار دەکات...',
    user: 'بەکارهێنەر',
    date: 'ڕۆژ',
    status: 'بارودۆخ',
    actions: 'کردار',
    approve: 'پەسەندکردن',
    reject: 'ڕەتکردنەوە',
    markReturned: 'نیشانکردنی گەڕاوە',
    noLoanRequests: 'هیچ داواکاری قەرز نییە.',
    failedUpdateStatus: 'نوێکردنەوەی بارودۆخ سەرکەفتو نەبوو.',
    pending: 'چاوەڕوان',
    approved: 'پەسەندکراو',
    returned: 'گەڕاوە',
    rejected: 'ڕەتکراوە',
    editProductNotesDescriptions: 'دەستکاری تێبینی و وەسفی بەرهەم',
    loadingProductsSimple: 'بەرهەمەکان بار دەکات...',
    description: 'وەسف',
    adminNotesInternal: 'تێبینی ئەدمین (ناوخۆ)',
    saveChanges: 'پاراستنی گۆڕانکارییەکان',
    productUpdated: 'تێبینی/وەسفی بەرهەم نوێ کرا!',
    productUpdateFailed: 'نوێکردنەوەی بەرهەم سەرکەفتو نەبوو.',
    uploadNewImageMock: 'بارکردنی وێنەی نوێ (Mock)',
    upload: 'بارکردن',
    uploading: 'بار دەکات...',
    mockUploadSuccess: 'بارکردنی وێنە بە سەرکەفتی تەواو بو!',
    uploadFailed: 'بارکردن سەرکەفتو نەبوو'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = useMemo(() => {
    return (key) => translations[language]?.[key] ?? translations.en[key] ?? key;
  }, [language]);

  useEffect(() => {
    document.body.setAttribute('data-lang', language);
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
